LexiconLMS/Controllers/CoursesController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using LexiconLMS.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;

namespace LexiconLMS.Controllers
{
    // Authorize roles Course Details -Anette
    [Authorize]
    public class CoursesController : Controller
    {
        private ApplicationUserManager _userManager;
        private readonly ApplicationDbContext db = new ApplicationDbContext();

        public CoursesController()
        {
        }

        public CoursesController(ApplicationUserManager userManager)
        {
            UserManager = userManager;
        }

        public ApplicationUserManager UserManager
        {
            get { return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>(); }
            private set { _userManager = value; }
        }

        // GET: Courses
        [Authorize(Roles = "Teacher")]
        public ActionResult Index()
        {
            return View(db.Courses.ToList());
        }

        // Get: Course/AddStudent 
        [Authorize(Roles = "Teacher")]
        public ActionResult AddStudent(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var course = new AddStudenToCourseModel();
            course.CourseId = (int) id;

            return View(course);
        }

        // Post: Courses/AddStudent
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Teacher")]
        public async Task<ActionResult> AddStudent(AddStudenToCourseModel model)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser
                {
                    UserName = model.Username,
                    Name = model.Name,
                    PhoneNumber = model.PhoneNumber,
                    Email = model.Email,
                    CourseId = model.CourseId
                };
                var course = db.Courses.Find(model.CourseId);
                course.Students.Add(user);
                var result = await UserManager.CreateAsync(user, model.Password);
                UserManager.AddToRole(UserManager.FindByEmail(user.Email).Id, "Student");
                if (result.Succeeded)
                {
                    // For more information on how to enable account confirmation and password reset please visit http://go.microsoft.com/fwlink/?LinkID=320771
                    // Send an email with this link
                    // string code = await UserManager.GenerateEmailConfirmationTokenAsync(user.Id);
                    // var callbackUrl = Url.Action("ConfirmEmail", "Account", new { userId = user.Id, code = code }, protocol: Request.Url.Scheme);
                    // await UserManager.SendEmailAsync(user.Id, "Confirm your account", "Please confirm your account by clicking <a href=\"" + callbackUrl + "\">here</a>");

                    return RedirectToAction("CourseDetails", new {id = course.CourseId});
                }
                AddErrors(result);
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }

        // GET: Courses/CourseDetails/
        public ActionResult CourseDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // GET: Courses/AddCourse
        [Authorize(Roles = "Teacher")]
        public ActionResult AddCourse(int? id)
        {
            return View();
        }

        // POST: Courses/AddCourse
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Teacher")]
        public ActionResult AddCourse([Bind(Include = "CourseId,Name,Description,StartDate")] Course course)
        {
            if (ModelState.IsValid)
            {
                db.Courses.Add(course);
                db.SaveChanges();
                return RedirectToAction("TeacherOverview", "Teacher");
            }

            return View(course);
        }

        // GET: Courses/EditCourse/5
        [Authorize(Roles = "Teacher")]
        public ActionResult EditCourse(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // POST: Courses/EditCourse/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Teacher")]
        public ActionResult EditCourse([Bind(Include = "CourseId,Name,Description,StartDate")] Course course)
        {
            if (ModelState.IsValid)
            {
                db.Entry(course).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("TeacherOverview", "Teacher");
            }
            return View(course);
        }

        // GET: Courses/DeleteCourse/5
        [Authorize(Roles = "Teacher")]
        public ActionResult DeleteCourse(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // POST: Courses/DeleteCourse/5
        [HttpPost, ActionName("DeleteCourse")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Teacher")]
        public ActionResult DeleteConfirmed(int id)
        {
            var course = db.Courses.Find(id);
            db.Courses.Remove(course);
            db.SaveChanges();
            return RedirectToAction("TeacherOverview", "Teacher");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Helpers

        // Used for XSRF protection when adding external logins
        private const string XsrfKey = "XsrfId";

        private IAuthenticationManager AuthenticationManager
        {
            get { return HttpContext.GetOwinContext().Authentication; }
        }

        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }
        }

        #endregion
    }
}

LexiconLMS/Controllers/ModulesController.cs
using System.Data.Entity;
using System.Net;
using System.Web.Mvc;
using LexiconLMS.Models;

namespace LexiconLMS.Controllers
{
    [Authorize]
    public class ModulesController : Controller
    {
        private readonly ApplicationDbContext db = new ApplicationDbContext();

        // GET: Modules/ModuleDetails/5
        public ActionResult ModuleDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var module = db.Modules.Find(id);
            if (module == null)
            {
                return HttpNotFound();
            }
            return View(module);
        }

        [Authorize(Roles = "Teacher")]
        // GET: Modules/AddModule
        public ActionResult AddModule(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "Name", id);
            var module = new Module {CourseId = (int) id};
            return View(module);
        }

        // POST: Modules/AddModule
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Teacher")]
        public ActionResult AddModule(
            [Bind(Include = "ModuleId,Name,Description,StartDate,EndDate,CourseId")] Module module)
        {
            if (ModelState.IsValid)
            {
                db.Modules.Add(module);
                db.SaveChanges();
                return RedirectToAction("CourseDetails", "Courses", new {id = module.CourseId});
            }

            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "Name", module.CourseId);
            return View(module);
        }

        // GET: Modules/EditModule/5
        [Authorize(Roles = "Teacher")]
        public ActionResult EditModule(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var module = db.Modules.Find(id);
            if (module == null)
            {
                return HttpNotFound();
            }
            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "Name", module.CourseId);
            return View(module);
        }

        // POST: Modules/EditModule/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Teacher")]
        public ActionResult EditModule(
            [Bind(Include = "ModuleId,Name,Description,StartDate,EndDate,CourseId")] Module module)
        {
            if (ModelState.IsValid)
            {
                db.Entry(module).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("CourseDetails", "Courses", new {id = module.CourseId});
            }
            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "Name", module.CourseId);
            return View(module);
        }

        // GET: Modules/DeleteModule/5
        [Authorize(Roles = "Teacher")]
        public ActionResult DeleteModule(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var module = db.Modules.Find(id);
            if (module == null)
            {
                return HttpNotFound();
            }
            return View(module);
        }

        // POST: Modules/DeleteModule/5
        [Authorize(Roles = "Teacher")]
        [HttpPost, ActionName("DeleteModule")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var module = db.Modules.Find(id);
            db.Modules.Remove(module);
            db.SaveChanges();
            return RedirectToAction("CourseDetails", "Courses", new {id = module.CourseId});
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LexiconLMS/Views/Courses/AddCourse.cshtml
@model LexiconLMS.Models.Course

@{
    ViewBag.Title = "AddCourse";
}

<h2>Add a Course</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Course</h4>
        <hr/>
        @Html.ValidationSummary(true, "", new {@class = "text-danger"})
        <div class="form-group">
            @Html.LabelFor(model => model.Name, new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Name, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Description, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.StartDate, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add" class="btn btn-default"/>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Teacher OverView", "TeacherOverview", "Teacher")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LexiconLMS/Views/Courses/AddStudent.cshtml
@model LexiconLMS.Models.AddStudenToCourseModel
@{
    ViewBag.Title = "Register";
}

<h2>@ViewBag.Title.</h2>

@using (Html.BeginForm("AddStudent", "Courses", FormMethod.Post, new {@class = "form-horizontal", role = "form"}))
{
    @Html.AntiForgeryToken()
    <h4>Create a new account.</h4>
    <hr/>
    @Html.ValidationSummary("", new {@class = "text-danger"})
    <div class="form-group">
        @Html.LabelFor(m => m.Username, new {@class = "col-md-2 control-label"})
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Username, new {@class = "form-control"})
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Name, new {@class = "col-md-2 control-label"})
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Name, new {@class = "form-control"})
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.PhoneNumber, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.PhoneNumber, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Password, new {@class = "col-md-2 control-label"})
        <div class="col-md-10">
            @Html.PasswordFor(m => m.Password, new {@class = "form-control"})
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.ConfirmPassword, new {@class = "col-md-2 control-label"})
        <div class="col-md-10">
            @Html.PasswordFor(m => m.ConfirmPassword, new {@class = "form-control"})
        </div>
    </div>
    <div class="form-group hidden">
        @Html.LabelFor(m => m.CourseId, new {@class = "col-md-2 control-label"})
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.CourseId, new {@class = "form-control"})
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Register"/>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LexiconLMS/Views/Courses/CourseDetails.cshtml
@using LexiconLMS.Models
@model LexiconLMS.Models.Course

@{
    ViewBag.Title = "CourseDetails";
}

<div>
    <ol class="breadcrumb h3">
        @if (User.IsInRole("Teacher"))
        {
            <li> @Html.ActionLink("Overview", "TeacherOverview", "Teacher") </li>
        }
        <li class="active">
            @Model.Name
        </li>
    </ol>
</div>

<hr />

<div>
    <h3>Course</h3>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @*@Html.DisplayFor(model => model.StartDate)*@
            @{ var startDate = Model.StartDate.ToString("yyyy-MM-dd"); }
            @Html.DisplayFor(modelItem => startDate)
        </dd>
    </dl>
</div>

@if (User.IsInRole("Teacher"))
{
    <p>
        @Html.ActionLink("Edit course", "EditCourse", new { id = Model.CourseId }) |
        @Html.ActionLink("Back to overview", "TeacherOverview", "Teacher")
    </p>
}
<hr />

<h4>Modules in course</h4>

<table class="table table-striped table-hover">
    @{
        var mod = new Module();
        <tr>
            <th>
                @Html.DisplayNameFor(model => mod.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => mod.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => mod.StartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => mod.EndDate)
            </th>
            <th></th>
        </tr>
    }

    @foreach (var module in Model.Modules)
    {
        <tr class="datarow" onclick="location.href = '@(Url.Action("ModuleDetails", "Modules", new {id = module.ModuleId}))'">
            <td>
                @Html.DisplayFor(modelItem => module.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => module.Description)
            </td>
            <td>
                @*Html.DisplayFor(modelItem => module.StartDate.ToString("yyyy-dd-MM"))*@
                @module.StartDate.ToString("yyyy-MM-dd")
            </td>
            <td>
                @*@Html.DisplayFor(modelItem => module.EndDate)*@
                @module.EndDate.ToString("yyyy-MM-dd")
            </td>
            <td>
                @if (User.IsInRole("Teacher"))
                {
                    @Html.ActionLink("Edit", "EditModule", "Modules", new {id = module.ModuleId}, null)
                    <span>|</span>
                    @Html.ActionLink("Delete", "DeleteModule", "Modules", new {id = module.ModuleId}, null)
                }
            </td>
        </tr>
    }

</table>

@if (User.IsInRole("Teacher"))
{
    <p>
        @Html.ActionLink("Add new module", "AddModule", "Modules", new { id = Model.CourseId }, null)
    </p>
}

<hr />

@*2016-06-29, ym: nedan: skapar kod för dokument*@


<h4>Documents in course</h4>

<table class="table table-striped table-hover">
    @{ var doc = new Document();}
    <tr>
        <th>
            @Html.DisplayNameFor(model => doc.Type)
        </th>
        <th>
            @Html.DisplayNameFor(model => doc.Description)
        </th>
        <th>
           Open file / Download
        </th>
        <th>
            @Html.DisplayNameFor(model => doc.TimeStamp)
        </th>
        <th>
            @Html.DisplayNameFor(model => doc.User.Name)
        </th>
        <th></th>
    </tr>

    @foreach (var document in Model.Documents)
    {
        <tr class="datarow" onclick="location.href = '@(Url.Action("DocumentDetails", "Documents", new {id = document.DocumentId}))'">
            <td>
                @*@Html.ActionLink("",modelItem => document.Name,)*@
                @Html.DisplayFor(modelItem => document.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => document.Description)
            </td>
            <td style="text-align: center">
                <a class="viewc" href="@Url.Action("OpenFile", "Documents", new { @fileName = document.Name })">
                    <img width="16" height="16" border="0" src="~/Images/view.jpg" class="viewc">
                </a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => document.TimeStamp)
            </td>
            <td>
                @Html.DisplayFor(modelItem => document.User.Name)
            </td>
            <td>
                @if (User.IsInRole("Teacher"))
                {   
                    @Html.ActionLink("Edit", "EditDocument", "Documents", new { id = document.DocumentId }, null)
                    <span>|</span>
                    @Html.ActionLink("Delete", "DeleteDocument", "Documents", new { id = document.DocumentId }, null)
                }
            </td>
        </tr>
    }

</table>

@if (User.IsInRole("Teacher"))
{
    <p>
        @Html.ActionLink("Upload new document", "AddDocument", "Documents", new { courseId = Model.CourseId }, null)
    </p>
}
<hr/>

@*2016-06-29, ym: ovan: skapar kod för dokument*@


<div>
    <h4>Students</h4>
    <dl class="dl-horizontal">

        @{int i = 0;

            foreach (var student in Model.Students.OrderBy(i2 => i2.Name).ToList())
            {

                i++;

                <dd>
                    <div style="padding-left: 10px;"> <b>@i: </b> @Html.ActionLink(student.Name, "ApplicationUserDetails", "Account", new { userId = student.Id }, null) </div>
                </dd>
            }
        }
    </dl>
    @if (User.IsInRole("Teacher"))
    {
        @Html.ActionLink("Add student to course", "AddStudent", new { id = Model.CourseId })
    }
</div>

@*2016-07-12 Anette - Moved Student to bottom in this view  *@
@*2016-07-12 YM - Added counter and links to student list*@

LexiconLMS/Views/Courses/Create.cshtml
@model LexiconLMS.Models.Course

@{
    ViewBag.Title = "Create";
}

<h2>Add a Course</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Course</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Teacher OverView", "TeacherOverview", "Teacher")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LexiconLMS/Views/Courses/Delete.cshtml
@model LexiconLMS.Models.Course

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Course</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

LexiconLMS/Views/Courses/DeleteCourse.cshtml
@model LexiconLMS.Models.Course

@{
    ViewBag.Title = "Delete course";
}

<h2>Delete course @Model.Name</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Course</h4>
    <hr/>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default"/> |
            @Html.ActionLink("Back to List", "TeacherOverview", "Teacher")
        </div>
    }
</div>

LexiconLMS/Views/Courses/Details.cshtml
@model LexiconLMS.Models.Course

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Course</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Students)
        </dt>
        @foreach (var student in Model.Students)
        {
            <dd>
                @Html.DisplayFor(modelItem => student.UserName)
            </dd>
        }
    </dl>
</div>

<div>
    @if (User.IsInRole("Teacher")){
        <hr />
        <h4>Add student</h4>
        @Html.ActionLink("Add student to course", "AddStudent", new { id = Model.CourseId} )
        <hr />
    }
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CourseId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

LexiconLMS/Views/Courses/Index.cshtml
@model IEnumerable<LexiconLMS.Models.Course>

@{
    ViewBag.Title = "Index";
}

<h2>Courses:</h2>

<p>
    @Html.ActionLink("Add new course", "AddCourse")
</p>
<table class="table table-striped table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartDate)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @*@Html.DisplayFor(modelItem => item.StartDate.ToString("yyyy-MM-dd"))*@
                @*@item.StartDate.ToString("yyyy-MM-dd")*@
                @{ var startDate = item.StartDate.ToString("yyyy-MM-dd"); }
                @Html.DisplayFor(modelItem => startDate)
            </td>
            <td>
                @Html.ActionLink("Edit", "EditCourse", new {id = item.CourseId}) |
                @Html.ActionLink("Details", "CourseDetails", new {id = item.CourseId}) |
                @Html.ActionLink("Delete", "DeleteCourse", new {id = item.CourseId})
            </td>
        </tr>

    @*@Html.ActionLink("Add new teacher", "AddTeacher")*@
    }




</table>