LexiconLMS/Models/Module.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace LexiconLMS.Models
{
    public class Module
    {
        public int ModuleId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }

        [Display(Name = "Start date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime StartDate { get; set; }

        [Display(Name = "End date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime EndDate { get; set; }

        public int CourseId { get; set; }
        public virtual Course Course { get; set; }
        public virtual ICollection<Activity> Activities { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
    }
}

LexiconLMS/Controllers/CoursesController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using LexiconLMS.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;

namespace LexiconLMS.Controllers
{
    // Authorize roles Course Details -Anette
    [Authorize]
    public class CoursesController : Controller
    {
        private ApplicationUserManager _userManager;
        private readonly ApplicationDbContext db = new ApplicationDbContext();

        public CoursesController()
        {
        }

        public CoursesController(ApplicationUserManager userManager)
        {
            UserManager = userManager;
        }

        public ApplicationUserManager UserManager
        {
            get { return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>(); }
            private set { _userManager = value; }
        }

        // GET: Courses
        [Authorize(Roles = "Teacher")]
        public ActionResult Index()
        {
            return View(db.Courses.ToList());
        }

        // Get: Course/AddStudent 
        [Authorize(Roles = "Teacher")]
        public ActionResult AddStudent(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var course = new AddStudenToCourseModel();
            course.CourseId = (int) id;

            return View(course);
        }

        // Post: Courses/AddStudent
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Teacher")]
        public async Task<ActionResult> AddStudent(AddStudenToCourseModel model)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser
                {
                    UserName = model.Username,
                    Name = model.Name,
                    PhoneNumber = model.PhoneNumber,
                    Email = model.Email,
                    CourseId = model.CourseId
                };
                var course = db.Courses.Find(model.CourseId);
                course.Students.Add(user);
                var result = await UserManager.CreateAsync(user, model.Password);
                UserManager.AddToRole(UserManager.FindByEmail(user.Email).Id, "Student");
                if (result.Succeeded)
                {
                    // For more information on how to enable account confirmation and password reset please visit http://go.microsoft.com/fwlink/?LinkID=320771
                    // Send an email with this link
                    // string code = await UserManager.GenerateEmailConfirmationTokenAsync(user.Id);
                    // var callbackUrl = Url.Action("ConfirmEmail", "Account", new { userId = user.Id, code = code }, protocol: Request.Url.Scheme);
                    // await UserManager.SendEmailAsync(user.Id, "Confirm your account", "Please confirm your account by clicking <a href=\"" + callbackUrl + "\">here</a>");

                    return RedirectToAction("CourseDetails", new {id = course.CourseId});
                }
                AddErrors(result);
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }

        // GET: Courses/CourseDetails/
        public ActionResult CourseDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // GET: Courses/AddCourse
        [Authorize(Roles = "Teacher")]
        public ActionResult AddCourse(int? id)
        {
            return View();
        }

        // POST: Courses/AddCourse
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Teacher")]
        public ActionResult AddCourse([Bind(Include = "CourseId,Name,Description,StartDate")] Course course)
        {
            if (ModelState.IsValid)
            {
                db.Courses.Add(course);
                db.SaveChanges();
                return RedirectToAction("TeacherOverview", "Teacher");
            }

            return View(course);
        }

        // GET: Courses/EditCourse/5
        [Authorize(Roles = "Teacher")]
        public ActionResult EditCourse(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // POST: Courses/EditCourse/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Teacher")]
        public ActionResult EditCourse([Bind(Include = "CourseId,Name,Description,StartDate")] Course course)
        {
            if (ModelState.IsValid)
            {
                db.Entry(course).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("TeacherOverview", "Teacher");
            }
            return View(course);
        }

        // GET: Courses/DeleteCourse/5
        [Authorize(Roles = "Teacher")]
        public ActionResult DeleteCourse(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // POST: Courses/DeleteCourse/5
        [HttpPost, ActionName("DeleteCourse")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Teacher")]
        public ActionResult DeleteConfirmed(int id)
        {
            var course = db.Courses.Find(id);
            db.Courses.Remove(course);
            db.SaveChanges();
            return RedirectToAction("TeacherOverview", "Teacher");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Helpers

        // Used for XSRF protection when adding external logins
        private const string XsrfKey = "XsrfId";

        private IAuthenticationManager AuthenticationManager
        {
            get { return HttpContext.GetOwinContext().Authentication; }
        }

        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }
        }

        #endregion
    }
}

LexiconLMS/Controllers/DocumentsController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using LexiconLMS.Models;
using System.IO;
using System.Web;
using System.Collections.Generic;
using Microsoft.Owin.Security.Provider;

namespace LexiconLMS.Controllers
{
    [Authorize]
    public class DocumentsController : Controller
    {
        private readonly ApplicationDbContext db = new ApplicationDbContext();

        // GET: Documents/DocumentDetails/5
        public ActionResult DocumentDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var document = db.Documents.Find(id);
            if (document == null)
            {
                return HttpNotFound();
            }
            return View(document);
        }

        // GET: Documents/AddDocument
        //2016-07-01, ym: nedan: ändrar på funktionen
        [Authorize]
        public ActionResult AddDocument(int? courseId, int? moduleId, int? activityId)
        {

            var course = new RegisterDocumentModel();

            if (courseId != null)
            {
                course.CourseId = (int)courseId;
            }

            if (moduleId != null)
            {
                course.ModuleId = (int)moduleId;
            }

            if (activityId != null)
            {
                course.ActivityId = (int)activityId;
            }

            if (User.IsInRole("Student"))
            {
                course.DocumentType = DocumentType.Inlämningsuppgift;
                return View("AddStudentExercise", course);
            }


            return View(course);
        }

        //2016-06-08/George C. / Added functionality for uploading a file + setting relevant properties for the uploade file
        // POST: Documents/AddDocument
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        //public ActionResult AddDocument (HttpPostedFileBase file_Uploader, Document document)
        public ActionResult AddDocument([Bind(Include = "FilePath,UploadedFile,DocumentType,Name,Type,Deadline,Description,CourseId,ModuleId,ActivityId")] RegisterDocumentModel document, HttpPostedFileBase UploadedFile)
        {
            string fileName = string.Empty;
            string destinationPath = string.Empty;

            if (document != null)
            {
                //string uploadedFile = string.Empty;
                //List<AddDocumentModel> uploadFiles = new List<AddDocumentModel>();
                //List<Document> AddDocumentModel = new List<Document>()
                fileName = Path.GetFileName(document.UploadedFile.FileName);
                destinationPath = Path.Combine(Server.MapPath("~/LMSDocuments/"), fileName);
                document.UploadedFile.SaveAs(destinationPath);


                if (Session["document"] != null)
                {
                    var isFileNameRepete = ((List<Document>)Session["document"]).Find(x => x.Name == fileName);
                    if (isFileNameRepete == null)
                    {
                        //uploadFiles.Add(new AddDocumentModel { Name = fileName, FilePath = destinationPath });
                        ((List<Document>)Session["document"]).Add(new Document { Name = fileName, FilePath = destinationPath });
                        ViewBag.Message = "File Uploaded Successfully";
                    }
                    else
                    {
                        ViewBag.Message = "File already exists";
                    }
                }
                else
                {
                    //uploadFiles.Add(new AddDocumentModel { Name = fileName, FilePath = destinationPath });
                    //Session["UpLoadedFile"] = uploadFiles;
                    ViewBag.Message = "File Uploaded Successfully";
                }
            }
            //    return View();
            //}

            if (ModelState.IsValid)
            {
                document.TimeStamp = DateTime.Now;

                var user = db.Users.FirstOrDefault(u => u.UserName == User.Identity.Name);
                document.UserId = user.Id;
                document.FilePath = destinationPath;
                document.Name = fileName;

                db.Documents.Add(new Document() { Name = document.Name, UserId = document.UserId, FilePath = document.FilePath, DocumentType = document.DocumentType,
                    Description = document.Description, TimeStamp = document.TimeStamp, Deadline = document.Deadline, CourseId = document.CourseId, ModuleId = document.ModuleId,
                    ActivityId = document.ActivityId, });
                db.SaveChanges();

                if (document.CourseId != null)
                {
                    return RedirectToAction("CourseDetails", "Courses", new { id = document.CourseId });
                }

                if (document.ModuleId != null)
                {
                    return RedirectToAction("ModuleDetails", "Modules", new { id = document.ModuleId });
                }

                if (document.ActivityId != null)
                {
                    return RedirectToAction("ActivityDetails", "Activities", new { id = document.ActivityId });
                }

                return RedirectToAction("CourseDetails", "Courses", new { id = document.CourseId });
                //return RedirectToAction("Index");
            }

            return RedirectToAction("AddDocument");
            //return View(document);
        }

        //2016-07-11/ George C. / Added open file - download functionality
        public FileResult OpenFile(string fileName)
        {
            try
            {
                return File(new FileStream(Server.MapPath("~/LMSDocuments/" + fileName), FileMode.Open), "application/octetstream", fileName);
            }

            catch (Exception ex)
            {
                throw ex;
            }
        }


        //2016-07-01, ym: ovan: ändrar på funktionen

        // GET: Documents/EditDocument/5
        [Authorize(Roles = "Teacher")]
        public ActionResult EditDocument(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var document = db.Documents.Find(id);

            if (document == null)
            {
                return HttpNotFound();
            }
            return View(document);
        }

        // POST: Documents/EditDocument/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Teacher")]
        public ActionResult EditDocument(
            [Bind(Include = "DocumentId,Name,Type,Description,TimeStamp,Uploader,CourseId,ModuleId,ActivityId")] Document document)
        {
            if (!ModelState.IsValid) return View(document);
            db.Entry(document).State = EntityState.Modified;
            db.SaveChanges();
            if (document.CourseId != null)
                return RedirectToAction("CourseDetails", "Courses", new { id = document.CourseId });
            if (document.ModuleId != null)
                return RedirectToAction("ModuleDetails", "Modules", new { id = document.ModuleId });
            if (document.ActivityId != null)
                return RedirectToAction("ActivityDetails", "Activities", new {id = document.ActivityId});
            return HttpNotFound();
        }

        // GET: Documents/DeleteDocument/5
        [Authorize(Roles = "Teacher")]
        public ActionResult DeleteDocument(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var document = db.Documents.Find(id);
            if (document == null)
            {
                return HttpNotFound();
            }
            return View(document);
        }

        // POST: Documents/DeleteDocument/5
        [HttpPost, ActionName("DeleteDocument")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Teacher")]
        public ActionResult DeleteConfirmed(int id)
        {
            var document = db.Documents.Find(id);
            try
            {
                if (document.CourseId != null)
                    return RedirectToAction("CourseDetails", "Courses", new { id = document.CourseId });
                if (document.ModuleId != null)
                    return RedirectToAction("ModuleDetails", "Modules", new { id = document.ModuleId });
                if (document.ActivityId != null)
                    return RedirectToAction("ActivityDetails", "Activities", new { id = document.ActivityId });
            }
            finally
            {
                db.Documents.Remove(document);
                db.SaveChanges();
            }
            return HttpNotFound();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LexiconLMS/Views/Modules/AddModule.cshtml
@model LexiconLMS.Models.Module

@{
    ViewBag.Title = "Add module";
}

<h2>Add module</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Module</h4>
        <hr/>
        @Html.ValidationSummary(true, "", new {@class = "text-danger"})
        <div class="form-group">
            @Html.LabelFor(model => model.Name, new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Name, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Description, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.StartDate, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.EndDate, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group hidden">
            @Html.LabelFor(model => model.CourseId, "CourseId", new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.DropDownList("CourseId", null, new {@class = "form-control"})
                @Html.ValidationMessageFor(model => model.CourseId, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default"/>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Course", "CourseDetails", "Courses", new {id = Model.CourseId}, null)
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LexiconLMS/Views/Modules/Create.cshtml
@model LexiconLMS.Models.Module

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Module</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group hidden">
            @Html.LabelFor(model => model.CourseId, "CourseId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CourseId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CourseId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Course", "CourseDetails", "Courses", new { id = Model.CourseId }, null)
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LexiconLMS/Views/Modules/Delete.cshtml
@model LexiconLMS.Models.Module

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Module</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Course.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to Course", "CourseDetails", "Courses", new { id = 1 }, null)
        </div>
    }
</div>

LexiconLMS/Views/Modules/ModuleDetails.cshtml
@using LexiconLMS.Models
@model LexiconLMS.Models.Module

@{
    ViewBag.Title = "Module details";
}

<div>
    <ol class="breadcrumb h3">
        @if (User.IsInRole("Teacher"))
        {
            <li> @Html.ActionLink("Overview", "TeacherOverview", "Teacher") </li>
        }
        <li> @Html.ActionLink(Model.Course.Name, "CourseDetails", "Courses", new { id = Model.CourseId }, null) </>
        <li class="active"> @Model.Name </li>
    </ol>
</div>

<hr />

<div>
    <h3>Module</h3>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Course.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @*@Html.DisplayFor(model => model.StartDate)*@
            @*@StartDate.ToString("yyyy-MM-dd")*@
            @{ var startDate = Model.StartDate.ToString("yyyy-MM-dd"); }
            @Html.DisplayFor(modelItem => startDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @*@Html.DisplayFor(model => model.EndDate)*@
            @*@EndDate.ToString("yyyy-MM-dd")*@
            @{ var endDate = Model.EndDate.ToString("yyyy-MM-dd"); }
            @Html.DisplayFor(modelItem => endDate)
        </dd>

    </dl>
</div>
<p>
    @if (User.IsInRole("Teacher"))
    {
        @Html.ActionLink("Edit", "EditModule", new { id = Model.ModuleId })
        <span>|</span>
    }
    @Html.ActionLink("Back to Course", "CourseDetails", "Courses", new { id = Model.CourseId }, null)
</p>

<hr />

<h4>Activities in module</h4>

@{ var activityInfo = Model.Activities.FirstOrDefault(); }
<table class="table table-striped table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(a => activityInfo.Type)
        </th>
        <th>
            @Html.DisplayNameFor(a => activityInfo.Description)
        </th>
        <th>
            @Html.DisplayNameFor(a => activityInfo.StartTime)
        </th>
        <th>
            @Html.DisplayNameFor(a => activityInfo.EndTime)
        </th>
        <th></th>
    </tr>

    @foreach (var activity in Model.Activities)
    {
        <tr class="datarow" onclick="location.href = '@(Url.Action("ActivityDetails", "Activities", new {id = activity.ActivityId}))'">
            <td>
                @Html.DisplayFor(modelItem => activity.Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => activity.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => activity.StartTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => activity.EndTime)
            </td>
            <td>
                @if (User.IsInRole("Teacher"))
                {
                    @Html.ActionLink("Edit", "EditActivity", "Activities", new { id = activity.ActivityId }, null)
                    <span>|</span>
                    @Html.ActionLink("Delete", "DeleteActivity", "Activities", new { id = activity.ActivityId }, null)
                }
            </td>
        </tr>
    }

</table>

@if (User.IsInRole("Teacher"))
{
    <p>
        @Html.ActionLink("Add new activity", "AddActivity", "Activities", new { id = Model.ModuleId }, null)
    </p>
} @*2016-07-04, ym: nedan: skapar kod för dokument*@<hr />

<h4>Documents in module</h4>

<table class="table table-striped table-hover">
    @{ var doc = new Document();}
    <tr>
        <th>
            @Html.DisplayNameFor(model => doc.Type)
        </th>
        <th>
            @Html.DisplayNameFor(model => doc.Description)
        </th>
        <th>
            Open file / Download
        </th>
        <th>
            @Html.DisplayNameFor(model => doc.TimeStamp)
        </th>
        <th>
            Uploader
        </th>
        <th></th>
    </tr>

    @foreach (var document in Model.Documents)
    {
        <tr class="datarow" onclick="location.href = '@(Url.Action("DocumentDetails", "Documents", new {id = document.DocumentId}))'">
            <td>
                @Html.DisplayFor(modelItem => document.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => document.Description)
            </td>
            <td style="text-align: center">
                <a class="viewc" href="@Url.Action("OpenFile", "Documents", new { @fileName = document.Name })">
                    <img width="16" height="16" border="0" src="~/Images/view.jpg" class="viewc">
                </a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => document.TimeStamp)
            </td>
            <td>
                @Html.DisplayFor(modelItem => document.User.Name)
            </td>
            <td>
                @if (User.IsInRole("Teacher"))
                {
                    @Html.ActionLink("Edit", "EditDocument", "Documents", new { id = document.DocumentId }, null)
                    <span>|</span>
                    @Html.ActionLink("Delete", "DeleteDocument", "Documents", new { id = document.DocumentId }, null)
                }
            </td>
        </tr>
    }

</table>

@if (User.IsInRole("Teacher"))
{
    <p>
        @Html.ActionLink("Upload New Document", "AddDocument", "Documents", new { moduleId = Model.ModuleId }, null)
    </p>
}
    @*2016-07-04, ym: ovan: skapar kod för dokument*@